language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
env:
  - SERVER_DIR=graphalyzer-server
install: 
    cd $SERVER_DIR && pip install -r requirements.txt
script: 
    python -m unittest src/test/Test* 
